version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: next_prisma_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next_prisma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - next_prisma_network

networks:
  next_prisma_network:

volumes:
  postgres_data:
